### ISSUE TITLE
 java.lang.UnsupportedOperationException remove in AttributeBrowser

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy2sbml#2]
Problem also existing in cy2sbml. Probably due to some change in the cytoscape.AttributeBrowser between Cytoscape v2.8.2 -> v2.8.3.

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException
 at java.util.AbstractList.remove(AbstractList.java:161)
    at java.util.AbstractList$Itr.remove(AbstractList.java:374)
    at java.util.AbstractList.removeRange(AbstractList.java:571)
    at java.util.AbstractList.clear(AbstractList.java:234)
    at browser.AttributeBrowser.getSelectedAttributes(AttributeBrowser.java:278)
```

**Comment by matthiaskoenig** [comment]
AttributeBrowser.setSelectedAttributes can not be called with Arrays.asList, but need a real list supporting all list operations.
